### ISSUE TITLE
Error: Map container not found

### ISSUE THREAD

**Issue by Captain-3D** [Virtuality360/360MapController#3]
NewClass._initContainer
src/map/Map.js:1103
  1100 | 	var container = this._container = DomUtil.get(id);
  1101 | 
  1102 | 	if (!container) {
> 1103 | 		throw new Error('Map container not found.');
       | ^  1104 | 	} else if (container._leaflet_id) {
  1105 | 		throw new Error('Map container is already initialized.');
  1106 | 	}

**Comment by DaltonChichester** [comment]
Fixed With most recent commit
